/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.neosavvy.user.dto.project {

    [Bindable]
    [RemoteClass(alias="com.neosavvy.user.dto.project.ClientCompany")]
    public dynamic class ClientCompany extends ClientCompanyBase {
        public function ClientCompany() {
            super();
        }

        public function get clientPointOfContact():String {
            return this.clientContact.lastName + "," + this.clientContact.firstName; 
        }

        public function get clientPhone():String {
            return this.clientContact.contactPhoneNumber;
        }

        public function get clientEmail():String {
            return this.clientContact.emailAddress;
        }

        
    }
}