/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BaseUserDTO.as).
 */

package com.neosavvy.user.dto {


    [Bindable]
    public class BaseUserDTOBase {


        private var _emailAddress:String;
        private var _firstName:String;
        private var _id:int;
        private var _lastName:String;
        private var _middleName:String;


        public function set emailAddress(value:String):void {
            _emailAddress = value;
        }
        public function get emailAddress():String {
            return _emailAddress;
        }

        public function set firstName(value:String):void {
            _firstName = value;
        }
        public function get firstName():String {
            return _firstName;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set lastName(value:String):void {
            _lastName = value;
        }
        public function get lastName():String {
            return _lastName;
        }

        public function set middleName(value:String):void {
            _middleName = value;
        }
        public function get middleName():String {
            return _middleName;
        }

        
    }
}