/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (CompanyDTO.as).
 */

package com.neosavvy.user.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class CompanyDTOBase {

        private var _addressOne:String;
        private var _addressTwo:String;
        private var _city:String;
        private var _companyName:String;
        private var _country:String;
        private var _id:int;
        private var _numEmployeesRange:NumEmployeesRangeDTO;
        private var _postalCode:String;
        private var _state:String;
        private var _userCompanyRoles:ListCollectionView;

        public function set addressOne(value:String):void {
            _addressOne = value;
        }
        public function get addressOne():String {
            return _addressOne;
        }

        public function set addressTwo(value:String):void {
            _addressTwo = value;
        }
        public function get addressTwo():String {
            return _addressTwo;
        }

        public function set city(value:String):void {
            _city = value;
        }
        public function get city():String {
            return _city;
        }

        public function set companyName(value:String):void {
            _companyName = value;
        }
        public function get companyName():String {
            return _companyName;
        }

        public function set country(value:String):void {
            _country = value;
        }
        public function get country():String {
            return _country;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set numEmployeesRange(value:NumEmployeesRangeDTO):void {
            _numEmployeesRange = value;
        }
        public function get numEmployeesRange():NumEmployeesRangeDTO {
            return _numEmployeesRange;
        }

        public function set postalCode(value:String):void {
            _postalCode = value;
        }
        public function get postalCode():String {
            return _postalCode;
        }

        public function set state(value:String):void {
            _state = value;
        }
        public function get state():String {
            return _state;
        }

        public function set userCompanyRoles(value:ListCollectionView):void {
            _userCompanyRoles = value;
        }
        public function get userCompanyRoles():ListCollectionView {
            return _userCompanyRoles;
        }

    }
}