/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (NumEmployeesRangeDTO.as).
 */

package com.neosavvy.user.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class NumEmployeesRangeDTOBase {


        private var _id:int;
        private var _rangeDescription:String;
        private var _rangeFrom:int;
        private var _rangeTo:int;


        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set rangeDescription(value:String):void {
            _rangeDescription = value;
        }
        public function get rangeDescription():String {
            return _rangeDescription;
        }

        public function set rangeFrom(value:int):void {
            _rangeFrom = value;
        }
        public function get rangeFrom():int {
            return _rangeFrom;
        }

        public function set rangeTo(value:int):void {
            _rangeTo = value;
        }
        public function get rangeTo():int {
            return _rangeTo;
        }

      
    }
}