/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (SecurityWrapperDTO.as).
 */

package com.neosavvy.user.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class SecurityWrapperDTOBase {

        private var _authorities:Array;
        private var _name:String;

        public function get authorities():Array {
            return _authorities;
        }

        public function set authorities(value:Array):void {
            _authorities = value;
        }

        public function set name(value:String):void {
            _name = value;
        }

        public function get name():String {
            return _name;
        }

    }
}