/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (UserCompanyRoleDTO.as).
 */

package com.neosavvy.user.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class UserCompanyRoleDTOBase {

        private var _company:CompanyDTO;
        private var _id:int;
        private var _role:RoleDTO;
        private var _user:UserDTO;

        public function set company(value:CompanyDTO):void {
            _company = value;
        }
        public function get company():CompanyDTO {
            return _company;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set role(value:RoleDTO):void {
            _role = value;
        }
        public function get role():RoleDTO {
            return _role;
        }

        public function set user(value:UserDTO):void {
            _user = value;
        }
        public function get user():UserDTO {
            return _user;
        }

    }
}