/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (UserInviteDTO.as).
 */

package com.neosavvy.user.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.meta;

    [Bindable]
    public class UserInviteDTOBase extends BaseUserDTO {

        private var _company:CompanyDTO;

        public function set company(value:CompanyDTO):void {
            _company = value;
        }
        public function get company():CompanyDTO {
            return _company;
        }

    }
}