/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (UserDTO.as).
 */

package com.neosavvy.user.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class UserDTOBase {// implements IExternalizable {

        private var _emailAddress:String;
        private var _firstName:String;
        private var _id:int;
        private var _lastName:String;
        private var _middleName:String;
        private var _password:String;
        private var _username:String;

        public function set emailAddress(value:String):void {
            _emailAddress = value;
        }
        public function get emailAddress():String {
            return _emailAddress;
        }

        public function set firstName(value:String):void {
            _firstName = value;
        }
        public function get firstName():String {
            return _firstName;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set lastName(value:String):void {
            _lastName = value;
        }
        public function get lastName():String {
            return _lastName;
        }

        public function set middleName(value:String):void {
            _middleName = value;
        }
        public function get middleName():String {
            return _middleName;
        }

        public function set password(value:String):void {
            _password = value;
        }
        public function get password():String {
            return _password;
        }

        public function set username(value:String):void {
            _username = value;
        }
        public function get username():String {
            return _username;
        }
//
//        public function readExternal(input:IDataInput):void {
//            _id = input.readObject() as int;
//            _firstName = input.readObject() as String;
//            _middleName = input.readObject() as String;
//            _lastName = input.readObject() as String;
//            _emailAddress = input.readObject() as String;
//            _username = input.readObject() as String;
//            _password = input.readObject() as String;
//        }
//
//        public function writeExternal(output:IDataOutput):void {
//            output.writeObject(_id);
//            output.writeObject(_firstName);
//            output.writeObject(_middleName);
//            output.writeObject(_lastName);
//            output.writeObject(_emailAddress);
//            output.writeObject(_username);
//            output.writeObject(_password);
//        }
    }
}