/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (UserDTO.as).
 */

package com.neosavvy.user.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class UserDTOBase {

        private var __laziness:String = null;

        private var _companies:ListCollectionView;
        private var _confirmedRegistration:Boolean;
        private var _emailAddress:String;
        private var _firstName:String;
        private var _id:int;
        private var _lastName:String;
        private var _middleName:String;
        private var _password:String;
        private var _registrationToken:String;
        private var _roles:ListCollectionView;
        private var _username:String;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is UserDTO) || (property as UserDTO).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set companies(value:ListCollectionView):void {
            _companies = value;
        }
        public function get companies():ListCollectionView {
            return _companies;
        }

        public function set confirmedRegistration(value:Boolean):void {
            _confirmedRegistration = value;
        }

        public function set emailAddress(value:String):void {
            _emailAddress = value;
        }
        public function get emailAddress():String {
            return _emailAddress;
        }

        public function set firstName(value:String):void {
            _firstName = value;
        }
        public function get firstName():String {
            return _firstName;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set lastName(value:String):void {
            _lastName = value;
        }
        public function get lastName():String {
            return _lastName;
        }

        public function set middleName(value:String):void {
            _middleName = value;
        }
        public function get middleName():String {
            return _middleName;
        }

        public function set password(value:String):void {
            _password = value;
        }
        public function get password():String {
            return _password;
        }

        public function set registrationToken(value:String):void {
            _registrationToken = value;
        }
        public function get registrationToken():String {
            return _registrationToken;
        }

        public function set roles(value:ListCollectionView):void {
            _roles = value;
        }
        public function get roles():ListCollectionView {
            return _roles;
        }

        public function set username(value:String):void {
            _username = value;
        }
        public function get username():String {
            return _username;
        }
//
//        public function readExternal(input:IDataInput):void {
//            _id = input.readObject() as int;
//            _firstName = input.readObject() as String;
//            _middleName = input.readObject() as String;
//            _lastName = input.readObject() as String;
//            _emailAddress = input.readObject() as String;
//            _username = input.readObject() as String;
//            _password = input.readObject() as String;
//        }
//
//        public function writeExternal(output:IDataOutput):void {
//            output.writeObject(_id);
//            output.writeObject(_firstName);
//            output.writeObject(_middleName);
//            output.writeObject(_lastName);
//            output.writeObject(_emailAddress);
//            output.writeObject(_username);
//            output.writeObject(_password);
//        }
    }
}