
DROP TABLE SVN_STATISTIC;

CREATE TABLE SVN_STATISTIC
(
AUTHOR VARCHAR(100) 
,REVISION NUMBER NOT NULL
,SVN_REPOSITORY_URL VARCHAR(1024) NOT NULL
,REV_DATE TIMESTAMP NOT NULL
,MESSAGE CLOB
,NUM_FILES_IN_REV NUMBER
,NUM_FILES_ADDED_IN_REV NUMBER
,NUM_FILES_DELETED_IN_REV NUMBER
,NUM_FILES_MODIFIED_IN_REV NUMBER
); 
ALTER TABLE SVN_STATISTIC ADD CONSTRAINT SVN_STATISTIC_PK PRIMARY KEY (REVISION,SVN_REPOSITORY_URL);