CREATE TABLE RH_TRIP
(
  TRIP_ID      NUMERIC(10)                       NOT NULL,
--   MEMBER_ID    NUMERIC(10)                       NOT NULL,
  CREATE_DATE  DATE                             NOT NULL,
--   TRIP_TYPE    VARCHAR(10)                NOT NULL,
  REASON_CODE  CHAR(1),
  PARTY_CODE   CHAR(1),
  -- moved description from trip type table temporarily
  DESCRIPTION  VARCHAR(100)               NOT NULL
);


CREATE TABLE RH_STATE_PROV
(
  CODE          VARCHAR(2)                NOT NULL,
  NAME          VARCHAR(100)              NOT NULL,
  COUNTRY_CODE  VARCHAR(2)
);


CREATE TABLE RH_REVIEW
(
  REVIEW_ID                NUMERIC(10)           NOT NULL,
  CREATION_DATE            DATE                 NOT NULL,
  TRIP_DATE                DATE                 NOT NULL,
  TRIP_ID                  NUMERIC(10)           NOT NULL,
  NUM_STOPS                NUMERIC(1),
  OUTBOUND_OR_RETURN_CODE  CHAR(1)     NOT NULL
);


CREATE TABLE RH_COUNTRY
(
  CODE          VARCHAR(10),
  COUNTRY_NAME  VARCHAR(100)
);


CREATE TABLE RH_AIRLINE
(
  AIRLINE_NAME    VARCHAR(100),
  ID              NUMERIC(10),
  DISPLAYED_NAME  VARCHAR(100),
  NUM_ROUTES      NUMERIC(5)
);


CREATE TABLE RH_AIRPORT
(
  CODE                       VARCHAR(3),
  LAT                        NUMERIC,
  LON                        NUMERIC,
  NAME                       VARCHAR(100),
  COUNTRY_CODE               VARCHAR(2),
  STATE_PROV                 VARCHAR(2),
  NUM_ROUTES                 NUMERIC(5),
  CITY                       VARCHAR(100),
  AIRPORT_WEBSITE            VARCHAR(100),
  WIKI                       VARCHAR(100),
  ADDITIONAL_SEARCH_PHRASES  VARCHAR(100),
  ID                         NUMERIC(10)         NOT NULL,
  CONSTRUCTED_NAME           VARCHAR(200)
);


CREATE TABLE RH_MEMBER
(
  MEMBER_ID                NUMERIC(10)           NOT NULL,
  USERNAME                 VARCHAR(50)    NOT NULL,
  LAST_NAME                VARCHAR(100)   NOT NULL,
  FIRST_NAME               VARCHAR(100)   NOT NULL,
  EMAIL_ADDRESS            VARCHAR(100)   NOT NULL,
  CITY                     VARCHAR(100)   NOT NULL,
  COUNTRY_CODE             VARCHAR(3)     NOT NULL,
  YEAR_BORN                NUMERIC(4)            NOT NULL,
  FLIGHTS_YEARLY           NUMERIC(4)            NOT NULL,
--   MEMBER_PHOTO             BLOB,
  ENCRYPTED_PASSWORD       VARCHAR(100),
  EMAIL_VERIFIED_YN        CHAR(1)     NOT NULL,
  EMAIL_VERIFIED_DATE      DATE,
  CREATION_DATE            DATE                 NOT NULL,
  AIRTRAVEL_ATTITUDE_CODE  VARCHAR(10)
);


CREATE TABLE RH_CABIN
(
  CODE         CHAR(1)                 NOT NULL,
  DESCRIPTION  VARCHAR(50)
);


CREATE TABLE RH_REVIEW_SEGMENT_CONTENT
(
  REVIEW_SEGMENT_ID  NUMERIC(10)                 NOT NULL,
  REVIEW_CONTENT_ID  NUMERIC(10)                 NOT NULL
);


CREATE TABLE RH_REVIEW_CONTENT
(
  ID                NUMERIC,
  REVIEW_TITLE      VARCHAR(2048),
  POSITIVE_CONTENT  VARCHAR(2048),
  NEGATIVE_CONTENT  VARCHAR(2048),
  TIPS_CONTENT      VARCHAR(2048)
);


CREATE TABLE RH_TRIP_TYPE
(
  CODE         CHAR(1)                 NOT NULL,
  DESCRIPTION  VARCHAR(100)               NOT NULL
);


CREATE TABLE RH_REVIEW_SEGMENT
(
  REVIEW_ID            NUMERIC(10)               NOT NULL,
  AIRLINE_ID           NUMERIC(10)               NOT NULL,
  AIRPORT_ORIG         VARCHAR(3)         NOT NULL,
  AIRPORT_DEST         VARCHAR(3)         NOT NULL,
  CABIN                CHAR(1)         NOT NULL,
  TRIP_DATE            DATE                     NOT NULL,
  RATING               CHAR(1)         NOT NULL,
  RATING_AIRPORT_ORIG  CHAR(1)         NOT NULL,
  RATING_AIRPORT_DEST  CHAR(1)         NOT NULL,
  ID                   NUMERIC(10)               NOT NULL,
  SEGMENT              NUMERIC(1),
  ROUTE_ID             NUMERIC(10)               NOT NULL
);


CREATE TABLE RH_RATING_CATEGORY_TYPE
(
  ID                  NUMERIC(10)                NOT NULL,
  RATING_CATEGORY_ID  NUMERIC(10),
  RATING_TYPE_ID      NUMERIC(10)                NOT NULL,
  DISPLAY_ORDER       NUMERIC(2)                 NOT NULL
);


CREATE TABLE RH_REVIEW_RATING
(
  RATING_ID           NUMERIC(10)                NOT NULL,
  REVIEW_ID           NUMERIC                    NOT NULL,
  RATING_TYPE_ID      NUMERIC(10)                NOT NULL,
  RATING              CHAR(1)          NOT NULL,
  RATING_CATEGORY_ID  NUMERIC(10)                NOT NULL,
  RATING_SEGMENT_ID   NUMERIC(10)
);


CREATE TABLE RH_RATING_TYPE
(
  ID           NUMERIC(10)                       NOT NULL,
  DESCRIPTION  VARCHAR(50)                NOT NULL
);


CREATE TABLE RH_RATING_CATEGORY
(
  ID           NUMERIC(10),
  DESCRIPTION  VARCHAR(50)                NOT NULL
);

--
-- ALTER TABLE RH_TRIP ADD (
--   PRIMARY KEY
-- (TRIP_ID));
--
-- ALTER TABLE RH_STATE_PROV ADD (
--   PRIMARY KEY
-- (CODE));

-- ALTER TABLE RH_REVIEW ADD (
--   CONSTRAINT RH_REVIEW_PK
--  PRIMARY KEY
--  (REVIEW_ID));
--
-- ALTER TABLE RH_COUNTRY ADD (
--   PRIMARY KEY
--  (CODE));
--
-- ALTER TABLE RH_AIRLINE ADD (
--   PRIMARY KEY
--  (ID));
--
-- ALTER TABLE RH_AIRPORT ADD (
--   PRIMARY KEY
--  (CODE));
--
-- ALTER TABLE RH_MEMBER ADD (
--   CONSTRAINT RH_MEMBERS_PK
--  PRIMARY KEY
--  (MEMBER_ID));
--
-- ALTER TABLE RH_CABIN ADD (
--   PRIMARY KEY
--  (CODE));
--
-- ALTER TABLE RH_REVIEW_CONTENT ADD (
--   PRIMARY KEY
--  (ID));
--
-- ALTER TABLE RH_TRIP_TYPE ADD (
--   PRIMARY KEY
--  (CODE));
--
-- ALTER TABLE RH_REVIEW_SEGMENT ADD (
--   PRIMARY KEY
--  (ID));
--
-- ALTER TABLE RH_REVIEW_RATING ADD (
--   CONSTRAINT RH_RATING_PK
--  PRIMARY KEY
--  (RATING_ID));
--
-- ALTER TABLE RH_RATING_TYPE ADD (
--   PRIMARY KEY
--  (ID));
--
-- ALTER TABLE RH_RATING_CATEGORY ADD (
--   PRIMARY KEY
--  (ID));
--
-- ALTER TABLE RH_TRIP ADD (
--   FOREIGN KEY (TRIP_TYPE)
--  REFERENCES RH_TRIP_TYPE (CODE),
--   FOREIGN KEY (MEMBER_ID)
--  REFERENCES RH_MEMBER (MEMBER_ID));
--
-- ALTER TABLE RH_REVIEW ADD (
--   FOREIGN KEY (TRIP_ID)
--  REFERENCES RH_TRIP (TRIP_ID));
--
-- ALTER TABLE RH_AIRPORT ADD (
--   FOREIGN KEY (COUNTRY_CODE)
--  REFERENCES RH_COUNTRY (CODE),
--   FOREIGN KEY (STATE_PROV)
--  REFERENCES RH_STATE_PROV (CODE));
--
-- ALTER TABLE RH_REVIEW_SEGMENT_CONTENT ADD (
--   FOREIGN KEY (REVIEW_SEGMENT_ID)
--  REFERENCES RH_REVIEW_SEGMENT (ID),
--   FOREIGN KEY (REVIEW_CONTENT_ID)
--  REFERENCES RH_REVIEW_CONTENT (ID));
--
-- ALTER TABLE RH_REVIEW_SEGMENT ADD (
--   FOREIGN KEY (REVIEW_ID)
--  REFERENCES RH_REVIEW (REVIEW_ID),
--   FOREIGN KEY (AIRPORT_ORIG)
--  REFERENCES RH_AIRPORT (CODE),
--   FOREIGN KEY (AIRPORT_DEST)
--  REFERENCES RH_AIRPORT (CODE),
--   FOREIGN KEY (CABIN)
--  REFERENCES RH_CABIN (CODE),
--   FOREIGN KEY (AIRLINE_ID)
--  REFERENCES RH_AIRLINE (ID),
--   FOREIGN KEY (ROUTE_ID)
--  REFERENCES RH_ROUTE (ID));
--
-- ALTER TABLE RH_RATING_CATEGORY_TYPE ADD (
--   FOREIGN KEY (RATING_CATEGORY_ID)
--  REFERENCES RH_RATING_CATEGORY (ID),
--   FOREIGN KEY (RATING_TYPE_ID)
--  REFERENCES RH_RATING_TYPE (ID));
--
-- ALTER TABLE RH_REVIEW_RATING ADD (
--   FOREIGN KEY (RATING_CATEGORY_ID)
--  REFERENCES RH_RATING_CATEGORY (ID),
--   FOREIGN KEY (RATING_SEGMENT_ID)
--  REFERENCES RH_REVIEW_SEGMENT (ID),
--   FOREIGN KEY (REVIEW_ID)
--  REFERENCES RH_REVIEW (REVIEW_ID),
--   FOREIGN KEY (RATING_TYPE_ID)
--  REFERENCES RH_RATING_TYPE (ID));
