/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.neosavvy.user.dto.project {

    [Bindable]
    [RemoteClass(alias="com.neosavvy.user.dto.project.ExpenseReport")]
    public dynamic class ExpenseReport extends ExpenseReportBase {
        public function ExpenseReport() {
            super();
        }

        public function get totalExpenseAmount():Number {
            var total:Number = 0;
            for each ( var expenseItem:ExpenseItem in expenseItems ) {
                total += expenseItem.amountNumber;
            }
            return total;
        }

        public function get totalReimbursableExpenseAmount():Number {
            var total:Number = 0;
            for each ( var expenseItem:ExpenseItem in expenseItems ) {
                if( expenseItem.paymentMethod.name == "Employee Paid")
                    total += expenseItem.amountNumber;
            }
            return total;
        }




    }
}