/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.neosavvy.svn.analytics.dto {
	import mx.collections.ArrayCollection;
	

    [Bindable]
    [RemoteClass(alias="com.neosavvy.svn.analytics.dto.SVNRepositoryDTO")]
    public class SVNRepositoryDTO extends SVNRepositoryDTOBase {
    	
    	private var _children:ArrayCollection;
    	
    	public function get children():ArrayCollection {
    		return _children;
    	}
    	
    	public function set children( children:ArrayCollection ):void{
    		_children = children;
    	}
    }
}