/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.neosavvy.user.dto.mobile {

    [Bindable]
    [RemoteClass(alias="com.neosavvy.user.dto.mobile.StatusDashboardData")]
    public dynamic class StatusDashboardData extends StatusDashboardDataBase {
        public function StatusDashboardData() {
            super();
        }

    }
}