package {
    import mx.collections.ArrayCollection;
    import mx.managers.ISystemManager;

    [Mixin]
    public class Counties {

        public static function init(systemManager:ISystemManager) : void {

            northCarolinaCounties.addItem(new County("Alamance") );
            northCarolinaCounties.addItem(new County("Alexander") );
            northCarolinaCounties.addItem(new County("Alleghany") );
            northCarolinaCounties.addItem(new County("Anson") );
            northCarolinaCounties.addItem(new County("Ashe") );
            northCarolinaCounties.addItem(new County("Avery") );
            northCarolinaCounties.addItem(new County("Beaufort") );
            northCarolinaCounties.addItem(new County("Bertie") );
            northCarolinaCounties.addItem(new County("Bladen") );
            northCarolinaCounties.addItem(new County("Brunswick") );
            northCarolinaCounties.addItem(new County("Buncombe") );
            northCarolinaCounties.addItem(new County("Burke") );
            northCarolinaCounties.addItem(new County("Cabarrus") );
            northCarolinaCounties.addItem(new County("Caldwell") );
            northCarolinaCounties.addItem(new County("Camden") );
            northCarolinaCounties.addItem(new County("Carteret") );
            northCarolinaCounties.addItem(new County("Caswell") );
            northCarolinaCounties.addItem(new County("Catawba") );
            northCarolinaCounties.addItem(new County("Chatham") );
            northCarolinaCounties.addItem(new County("Cherokee") );
            northCarolinaCounties.addItem(new County("Chowan") );
            northCarolinaCounties.addItem(new County("Clay") );
            northCarolinaCounties.addItem(new County("Cleveland") );
            northCarolinaCounties.addItem(new County("Columbus") );
            northCarolinaCounties.addItem(new County("Craven") );
            northCarolinaCounties.addItem(new County("Cumberland") );
            northCarolinaCounties.addItem(new County("Currituck") );
            northCarolinaCounties.addItem(new County("Dare") );
            northCarolinaCounties.addItem(new County("Davidson") );
            northCarolinaCounties.addItem(new County("Davie") );
            northCarolinaCounties.addItem(new County("Duplin") );
            northCarolinaCounties.addItem(new County("Durham") );
            northCarolinaCounties.addItem(new County("Edgecombe") );
            northCarolinaCounties.addItem(new County("Forsyth") );
            northCarolinaCounties.addItem(new County("Franklin") );
            northCarolinaCounties.addItem(new County("Gaston") );
            northCarolinaCounties.addItem(new County("Gates") );
            northCarolinaCounties.addItem(new County("Graham") );
            northCarolinaCounties.addItem(new County("Granville") );
            northCarolinaCounties.addItem(new County("Greene") );
            northCarolinaCounties.addItem(new County("Guilford") );
            northCarolinaCounties.addItem(new County("Halifax") );
            northCarolinaCounties.addItem(new County("Harnett") );
            northCarolinaCounties.addItem(new County("Haywood") );
            northCarolinaCounties.addItem(new County("Henderson") );
            northCarolinaCounties.addItem(new County("Hertford") );
            northCarolinaCounties.addItem(new County("Hoke") );
            northCarolinaCounties.addItem(new County("Hyde") );
            northCarolinaCounties.addItem(new County("Iredell") );
            northCarolinaCounties.addItem(new County("Jackson") );
            northCarolinaCounties.addItem(new County("Johnston") );
            northCarolinaCounties.addItem(new County("Jones") );
            northCarolinaCounties.addItem(new County("Lee") );
            northCarolinaCounties.addItem(new County("Lenoir") );
            northCarolinaCounties.addItem(new County("Lincoln") );
            northCarolinaCounties.addItem(new County("Macon") );
            northCarolinaCounties.addItem(new County("Madison") );
            northCarolinaCounties.addItem(new County("Martin") );
            northCarolinaCounties.addItem(new County("McDowell") );
            northCarolinaCounties.addItem(new County("Mecklenburg") );
            northCarolinaCounties.addItem(new County("Mitchell") );
            northCarolinaCounties.addItem(new County("Montgomery") );
            northCarolinaCounties.addItem(new County("Moore") );
            northCarolinaCounties.addItem(new County("Nash") );
            northCarolinaCounties.addItem(new County("New Hanover") );
            northCarolinaCounties.addItem(new County("Northampton") );
            northCarolinaCounties.addItem(new County("Onslow") );
            northCarolinaCounties.addItem(new County("Orange") );
            northCarolinaCounties.addItem(new County("Pamlico") );
            northCarolinaCounties.addItem(new County("Pasquotank") );
            northCarolinaCounties.addItem(new County("Pender") );
            northCarolinaCounties.addItem(new County("Perquimans") );
            northCarolinaCounties.addItem(new County("Person") );
            northCarolinaCounties.addItem(new County("Pitt") );
            northCarolinaCounties.addItem(new County("Polk") );
            northCarolinaCounties.addItem(new County("Randolph") );
            northCarolinaCounties.addItem(new County("Richmond") );
            northCarolinaCounties.addItem(new County("Robeson") );
            northCarolinaCounties.addItem(new County("Rockingham") );
            northCarolinaCounties.addItem(new County("Rowan") );
            northCarolinaCounties.addItem(new County("Rutherford") );
            northCarolinaCounties.addItem(new County("Sampson") );
            northCarolinaCounties.addItem(new County("Scotland") );
            northCarolinaCounties.addItem(new County("Stanly") );
            northCarolinaCounties.addItem(new County("Stokes") );
            northCarolinaCounties.addItem(new County("Surry") );
            northCarolinaCounties.addItem(new County("Swain") );
            northCarolinaCounties.addItem(new County("Transylvania") );
            northCarolinaCounties.addItem(new County("Tyrrell") );
            northCarolinaCounties.addItem(new County("Union") );
            northCarolinaCounties.addItem(new County("Vance") );
            northCarolinaCounties.addItem(new County("Wake") );
            northCarolinaCounties.addItem(new County("Warren") );
            northCarolinaCounties.addItem(new County("Washington") );
            northCarolinaCounties.addItem(new County("Watauga") );
            northCarolinaCounties.addItem(new County("Wayne") );
            northCarolinaCounties.addItem(new County("Wilkes") );
            northCarolinaCounties.addItem(new County("Wilson") );
            northCarolinaCounties.addItem(new County("Yadkin") );
            northCarolinaCounties.addItem(new County("Yancey") );

            southCarolinaCounties.addItem(new County("Abbeville"));
            southCarolinaCounties.addItem(new County("Aiken"));
            southCarolinaCounties.addItem(new County("Allendale"));
            southCarolinaCounties.addItem(new County("Anderson"));
            southCarolinaCounties.addItem(new County("Bamberg"));
            southCarolinaCounties.addItem(new County("Barnwell"));
            southCarolinaCounties.addItem(new County("Beaufort"));
            southCarolinaCounties.addItem(new County("Berkeley"));
            southCarolinaCounties.addItem(new County("Calhoun"));
            southCarolinaCounties.addItem(new County("Charleston"));
            southCarolinaCounties.addItem(new County("Cherokee"));
            southCarolinaCounties.addItem(new County("Chester"));
            southCarolinaCounties.addItem(new County("Chesterfield"));
            southCarolinaCounties.addItem(new County("Clarendon"));
            southCarolinaCounties.addItem(new County("Colleton"));
            southCarolinaCounties.addItem(new County("Darlington"));
            southCarolinaCounties.addItem(new County("Dillon"));
            southCarolinaCounties.addItem(new County("Dorchester"));
            southCarolinaCounties.addItem(new County("Edgefield"));
            southCarolinaCounties.addItem(new County("Fairfield"));
            southCarolinaCounties.addItem(new County("Florence"));
            southCarolinaCounties.addItem(new County("Georgetown"));
            southCarolinaCounties.addItem(new County("Greenville"));
            southCarolinaCounties.addItem(new County("Greenwood"));
            southCarolinaCounties.addItem(new County("Hampton"));
            southCarolinaCounties.addItem(new County("Horry"));
            southCarolinaCounties.addItem(new County("Jasper"));
            southCarolinaCounties.addItem(new County("Kershaw"));
            southCarolinaCounties.addItem(new County("Lancaster"));
            southCarolinaCounties.addItem(new County("Laurens"));
            southCarolinaCounties.addItem(new County("Lee"));
            southCarolinaCounties.addItem(new County("Lexington"));
            southCarolinaCounties.addItem(new County("Marion"));
            southCarolinaCounties.addItem(new County("Marlboro"));
            southCarolinaCounties.addItem(new County("McCormick"));
            southCarolinaCounties.addItem(new County("Newberry"));
            southCarolinaCounties.addItem(new County("Oconee"));
            southCarolinaCounties.addItem(new County("Orangeburg"));
            southCarolinaCounties.addItem(new County("Pickens"));
            southCarolinaCounties.addItem(new County("Richland"));
            southCarolinaCounties.addItem(new County("Saluda"));
            southCarolinaCounties.addItem(new County("Spartanburg"));
            southCarolinaCounties.addItem(new County("Sumter"));
            southCarolinaCounties.addItem(new County("Union"));
            southCarolinaCounties.addItem(new County("Williamsburg"));
            southCarolinaCounties.addItem(new County("York"));
        }

        public static var northCarolinaCounties:ArrayCollection = new ArrayCollection();

        public static var southCarolinaCounties:ArrayCollection = new ArrayCollection();

    }
}