/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.neosavvy.user.dto.project {

    [Bindable]
    [RemoteClass(alias="com.neosavvy.user.dto.project.ExpenseItem")]
    public dynamic class ExpenseItem extends ExpenseItemBase {
        public function ExpenseItem() {
            super();
        }

        public function clone():ExpenseItem
        {
            var expenseItem : ExpenseItem = new ExpenseItem();

            expenseItem.expenseDate = new Date(expenseDate);
            expenseItem.amount = new Number(amountNumber);
            expenseItem.expenseItemType = expenseItemType;
            expenseItem.expenseReport = expenseReport;
            expenseItem.paymentMethod = paymentMethod;
            expenseItem.projectType = projectType;
            
            return expenseItem;
        }
    }
}