/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.neosavvy.user.dto.project {

    [Bindable]
    [RemoteClass(alias="com.neosavvy.user.dto.project.ExpenseItemValue")]
    public dynamic class ExpenseItemValue extends ExpenseItemValueBase {
        public function ExpenseItemValue() {
            super();
        }

    }
}