/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.neosavvy.user.dto.project {

    [Bindable]
    [RemoteClass(alias="com.neosavvy.user.dto.project.ExpenseReport")]
    public dynamic class ExpenseReport extends ExpenseReportBase {
        public function ExpenseReport() {
            super();
        }

        public var displayStringOverride : String;

        public function get displayString():String
        {
            if( displayStringOverride )
            {
                return displayStringOverride;
            }
            else if( project && project.name)
            {
                return "(" + idNumber + ")" + project.name;
            }
            else if ( project && project.name && location)
            {
                return "(" + idNumber + ")" + project.name + " " + location;
            }
            else
            {
                return "(" + idNumber + ")";
            }
        }

    }
}