/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.neosavvy.svn.analytics.dto.file {
	import mx.collections.ArrayCollection;
	

    [Bindable]
    [RemoteClass(alias="com.neosavvy.svn.analytics.dto.file.DirectoryNode")]
    public class DirectoryNode extends DirectoryNodeBase {
    	
    	private var _children:ArrayCollection;
    	
    	public function get children():ArrayCollection {
    		return _children;
    	}
    	
    	public function set children( children:ArrayCollection ):void {
    		_children = children;
    	}
    	
    	public function addDirectoryAsChild( directory:DirectoryNode ):void {
    		if( !_children ) {
    			_children = new ArrayCollection();
    		}
    		_children.addItem( directory );
    	}
    	
    	public function addFileAsChild( file:FileNode ):void {
    		if( !_children ) {
    			_children = new ArrayCollection();
    		}
    		_children.addItem( file );
    	}
    	
    	public function addChildren( childrenToAdd:Array ):void {
    		for each ( var child:Object in childrenToAdd ) {
    			if( child is DirectoryNode ) {
    				addDirectoryAsChild( child as DirectoryNode );
    			} 
    			else if( child is FileNode ) {
    				addFileAsChild( child as FileNode );
    			}
    		}
    	}
    }
}