/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.neosavvy.user.service.exception {

    [Bindable]
    [RemoteClass(alias="com.neosavvy.user.service.exception.MobileServiceException")]
    public dynamic class MobileServiceException extends MobileServiceExceptionBase {
        public function MobileServiceException() {
            super();
        }

    }
}