/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.neosavvy.user.dto.companyManagement {

    [Bindable]
    [RemoteClass(alias="com.neosavvy.user.dto.companyManagement.UserDTO")]
    public class UserDTO extends UserDTOBase {

        public function get fullName():String {
            return super.lastName + ", " + super.firstName;
        }


        public function toString():String {
            return "UserDTOBase{_active=" + String(active) +
                   ",confirmedRegistration=" + String(confirmedRegistration) +
                   ",id=" + String(id) +
                   ",password=" + String(password) +
                   ",registrationToken=" + String(registrationToken) +
                   ",userCompanyRoles=" + String(userCompanyRoles) +
                   ",username=" + String(username) + "}";
        }
    }
}