/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package fineline.focal.common.types.v1 {

    [Bindable]
    [RemoteClass(alias="fineline.focal.common.types.v1.ScratchFileRef")]
    public dynamic class ScratchFileRef extends ScratchFileRefBase {
        public function ScratchFileRef() {
            super();
        }

    }
}