/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package fineline.focal.common.types.v1 {
    import com.neosavvy.user.ProxyConstants;

    [Bindable]
    [RemoteClass(alias="fineline.focal.common.types.v1.StorageServiceFileRef")]
    public dynamic class StorageServiceFileRef extends StorageServiceFileRefBase {
        public function StorageServiceFileRef() {
            super();
        }

        public function get source():String
        {
            var returnValue : String = ProxyConstants.getUrlForEnvironment() +
                        "/nets/storage/file/" +
                        bucket + "/" +
                        key +
                        "?noCache=" + (new Date().getMilliseconds());

            return returnValue;
        }


    }
}